version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
    commit-message:
      prefix: "gh-action"
    groups:
      all:
        patterns:
          - "*"

  - package-ecosystem: "gradle"
    directory: "/"
    schedule:
      interval: "weekly"
    commit-message:
      prefix: "gradle"
    groups:
      minor:
        patterns:
          - "*"
        update-types:
          - "minor"
          - "patch"

  - package-ecosystem: "gradle"
    directory: "example"
    schedule:
      interval: "weekly"
    commit-message:
      prefix: "gradle"
    groups:
      minor:
        patterns:
          - "*"
        update-types:
          - "minor"
          - "patch"

  - package-ecosystem: "gradle"
    directory: "example"
    schedule:
      interval: "weekly"
    commit-message:
      prefix: "client"
    groups:
      minor:
        patterns:
          - "*"
        update-types:
          - "minor"
          - "patch"
