name: Publish

on:
  pull_request:
    branches:
      - main
#    types:
#      - closed

concurrency:
  group: ${{ github.ref }}-${{ github.workflow }}
  cancel-in-progress: true

jobs:
  publish:
#    if: github.event.pull_request.merged == true && startsWith(github.head_ref, 'release/')
    runs-on: ubuntu-latest
    environment: Production
    steps:
      - name: Checkout TIKI Publish Client
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Checkout PR
        id: getpr
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          gh pr checkout ${{ github.event.pull_request.number }}
          export PR_BRANCH=$(git branch --show-current)
          echo "branch=$PR_BRANCH" >> $GITHUB_OUTPUT
          git log

      - name: Get Version
        id: semver
        uses: ietf-tools/semver-action@v1
        with:
          token: ${{ github.token }}
          branch: ${{ steps.getpr.outputs.branch }}

      - name: Set up Java
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'adopt'

      - name: Setup Android SDK
        uses: android-actions/setup-android@v3

      - name: Validate Gradle Wrapper
        uses: gradle/wrapper-validation-action@v1

      - name: Release
        uses: ncipollo/release-action@v1
        with:
          tag: ${{ steps.semver.outputs.nextStrict }}

      - name: "Publish"
        uses: gradle/gradle-build-action@v2
        with:
          arguments: publishReleasePublicationToOSSRHRepository
        env:
          OSSRH_USER: ${{ secrets.OSSRH_USER }}
          OSSRH_TOKEN: ${{ secrets.OSSRH_TOKEN }}
          PGP_PRIVATE_KEY: ${{ secrets.PGP_PRIVATE_KEY }}
          PGP_PASSPHRASE: ${{ secrets.PGP_PASSPHRASE }}